### ISSUE TITLE
The backend

### ISSUE THREAD

**Issue by jacknoble** [rorysaur/quack#14]
Not a priority but I'd like to have a conversation about using something other than firebase. Or using firebase as just bridge to a custom backend. I'm partial to http://www.phoenixframework.org/ for killer websocket support but could maybe talked into something else, clojure?. 

Just feel like rolling our own is the #truepath.

**Comment by rorysaur** [comment]
the reasoning behind firebase was simply "let's use something that supports realtime push and requires as little brainpower as possible so that we can focus on learning new frontendy concepts and not get overwhelmed." if you're feeling ambitious, of course we can roll our own.. but yeah, let's look into multiple things and pick whatever the majority of peeps are most excited about learning.

**Comment by rorysaur** [comment]
https://news.ycombinator.com/item?id=8671618

**Comment by jacknoble** [comment]
If firebase is going to be quick then it makes sense as something for us to bootstrap off of. Were you thinking node to host it?

**Comment by jacknoble** [comment]
Hmm, https://www.firebase.com/docs/web/libraries/react/guide.html looks easy... but it basically replaces all of flux and just leaves us with the view layer. It also seems like a bad design thats going to force way too much logic into the callbacks of react components and won't handle store synchronization well (no "wait for"). It's really powerful but I'm not sure we'll learn anything with it. Also, no react server-side rendering :-(

**Comment by rorysaur** [comment]
hm.. do you think it could work to just integrate it into flux, like only interact with firebase in the same place where you would normally make backend calls? or should we do something else. what are the alternatives for a realtime backend? node and phoenix?

**Comment by cjavdev** [comment]
I've been thinking about this a lot. if the web api module encapsulates the calls enough it should really act as the backend adapter and make all the calls.

**Comment by rorysaur** [comment]
i'm working on this now because i just realized that it's necessary for my other ticket, allowing multiple users, which didn't occur to me before because i'm a dum-dum.

**Comment by rorysaur** [comment]
this is an example firebase db to show our "schema" (work in progress).. i needed to make some notes while thinking about it, also you can see what i'm thinking and comment on it.

it uses ideas and recommendations from:
https://www.firebase.com/docs/web/guide/structuring-data.html

the gibberish keys are unique ids, which firebase automatically generates if you use `push` instead of `set` (i.e., if you don't provide your own key).

channels-messages are associated by the messages being categorized/bucketed by channel.
users-channels is the two-way relationship discussed in the link above.
users-messages are associated by each message having a reference to the user id.

UPDATE: we can use unique usernames instead of generated ones.. later these can serve as logins.
UPDATE: bucket messages by channel instead of user. add user reference to message properties. change "main" channel to "bestcohort" to be more vivid :)

```
users: {
  rorysaur: {
    name: "rory", // this isn't the unique id since it can be changed with /nick
    channels: {
      bestcohort: true // this is an "index" as recommended by firebase docs
    }
  },
  jacknoble: {
    name: "jack",
    channels: {
      bestcohort: true
    }
  }
},

channels: {
  bestcohort: {
    users: {
      wkejfak: "rorysaur", // rory's unique id
      iasudsd: "jacknoble", // jack's unique id
    }
  }
},

messages: {
  bestcohort: {
    qeouqdfue: {
      timestamp: 123456789,
      text: "hi",
      user: "rorysaur"
    }
  }
}
```

**Comment by jacknoble** [comment]
_Should_ messages be bucked under user? It seems more intuitive to me to bucket them under channel and give them an associated user_id. I don't know if there are performance concerns here but "get me the last 100 messages in this channel" is going to be run a lot more times than "get me the last 100 messages from this user".

**Comment by rorysaur** [comment]
yeah, that's a good point. let's go with that. and maybe "get me the last 100 messages from this user" won't happen at all.. in that case, the message's user_id can be purely for displaying the user's name and whatnot

**Comment by rorysaur** [comment]
see updated.

**Comment by jacknoble** [comment]
:+1:

**Comment by rorysaur** [comment]
closing cuz all the relevant info here can now be found in the readme.
